LunchOrderingApp/Models/Domain/Dish.cs
#nullable disable
using System.ComponentModel.DataAnnotations.Schema;

namespace LunchOrderingApp.Models.Domain
{
    public class Dish
    {
        public int DishId { get; set; }
        public string DishName { get; set; }
        public string DishDescription { get; set;}
        public byte[] DishImage { get; set; }
        [ForeignKey(nameof(Domain.Menu.MenuId))]
        public int MenuId { get; set; }
        public Menu Menu { get; set; }
    }
}

LunchOrderingApp/Controllers/DishController.cs
using LunchOrderingApp.Interfaces;
using LunchOrderingApp.Models.ViewModels.DishViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace LunchOrderingApp.Controllers
{
    public class DishController : Controller
    {
        private readonly IDishRepository _dishRepository;

        public DishController(IDishRepository dishRepository)
        {
            _dishRepository = dishRepository;
        }
        public async Task<IActionResult> Index(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;
            var dishes = await _dishRepository.GetDishes(searchString);
            return View(dishes);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Add()
        {
            ViewBag.Menus = await _dishRepository.GetMenus();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(CreateAndEditDishVM dishVM)
        {
            ViewBag.Menus = await _dishRepository.GetMenus();
            if (ModelState.IsValid)
            {
                await _dishRepository.AddDish(dishVM);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Photo upload failed");
            }
            return View(dishVM);
        }
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.Menus = await _dishRepository.GetMenus();
            var dish = await _dishRepository.GetDishById(id);
            if (dish is null)
            {
                return View("Error");
            }
            return View(dish);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, CreateAndEditDishVM dishVM)
        {
            ViewBag.Menus = await _dishRepository.GetMenus();
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit dish");
                return View("Edit", dishVM);
            }
            if (await _dishRepository.UpdateDish(id, dishVM))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(await _dishRepository.GetDishById(id));
            }
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await _dishRepository.DeleteDish(id);
            return RedirectToAction("Index");
        }
    }
}

LunchOrderingApp/Views/Dish/Add.cshtml
@using LunchOrderingApp.Models.ViewModels.DishViewModels
@model CreateAndEditDishVM
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<section class="p-5 mt-4">
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
                <div class="card text-black" style="border-radius: 25px;">
                    <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                            <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Add new restaurant</p>
                                <form asp-action="Add" method="post" class="mx-1 mx-md-4" enctype="multipart/form-data">
                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <div class="form-outline flex-fill mb-0">
                                            <input aria-required="true" asp-for="DishName" type="text" class="form-control" />
                                            <label asp-for="DishName" class="form-label">Dish Name</label>
                                            <span asp-validation-for="DishName" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <div class="form-outline flex-fill mb-0">
                                            <textarea aria-required="true" asp-for="DishDescription" type="text" class="form-control md-textarea" rows="3"></textarea>
                                            <label asp-for="DishDescription" class="form-label">Dish Description</label>
                                            <span asp-validation-for="DishDescription" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <div class="form-outline flex-fill mb-0 file-upload-wrapper">
                                            <input aria-required="true" asp-for="DishImage"  type="file" class="form-control " />
                                            <span asp-validation-for="DishImage" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <div class="form-outline flex-fill mb-0">
                                            <label asp-for="MenuId">Menu</label>
                                            <select asp-for="MenuId" class="form-select">
                                                <option selected disabled>--Select--</option>
                                                @foreach (var menu in ViewBag.Menus)
                                                {
                                                    <option value="@menu.MenuId">@menu.MenuName</option>
                                                }
                                            </select>
                                        </div>
                                    </div>
                                    <div class="d-flex w-100 justify-content-center">
                                        <button type="submit" class="btn btn-primary mx-3 btn">Add</button>
                                        <a asp-controller="Dish" asp-action="Index" class="btn mx-3 btn-danger">Cancel</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

LunchOrderingApp/Views/Dish/Edit.cshtml
@using LunchOrderingApp.Models.ViewModels.DishViewModels
@model DishVM
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<section class="p-5 mt-4">
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
                <div class="card text-black" style="border-radius: 25px;">
                    <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                            <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Add new restaurant</p>
                                <form asp-action="Edit" method="post" class="mx-1 mx-md-4" enctype="multipart/form-data">
                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <div class="form-outline flex-fill mb-0">
                                            <input aria-required="true" asp-for="DishName" type="text" class="form-control" />
                                            <label asp-for="DishName" class="form-label">Dish Name</label>
                                            <span asp-validation-for="DishName" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <div class="form-outline flex-fill mb-0">
                                            <textarea aria-required="true" asp-for="DishDescription" type="text" class="form-control md-textarea" rows="3"></textarea>
                                            <label asp-for="DishDescription" class="form-label">Dish Description</label>
                                            <span asp-validation-for="DishDescription" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <div class="form-outline flex-fill mb-0 file-upload-wrapper">
                                            <input aria-required="true" asp-for="DishImage" type="file" class="form-control" />
                                            <span asp-validation-for="DishImage" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <div class="form-outline flex-fill mb-0">
                                            <label asp-for="MenuId">Menu</label>
                                            <select asp-for="MenuId" class="form-select">
                                                @foreach (var menu in ViewBag.Menus)
                                                {
                                                    <option value="@menu.MenuId">@menu.MenuName</option>
                                                }
                                            </select>
                                        </div>
                                    </div>
                                    <div class="d-flex w-100 justify-content-center">
                                        <button type="submit" class="btn btn-primary mx-3 btn">Save</button>
                                        <a asp-controller="Dish" asp-action="Index" class="btn mx-3 btn-warning">Cancel</a>
                                        <a asp-action="Delete" asp-controller="Dish" asp-route-id="@Model.DishId" type="submit" class="my-auto btn-danger btn">Delete</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

LunchOrderingApp/Views/Dish/Index.cshtml
@using LunchOrderingApp.Models.ViewModels.DishViewModels
@model IEnumerable<DishVM>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

@*
    How to convert byte array to image for display
https://www.c-sharpcorner.com/article/mvc-display-image-from-byte-array/
*@

<div class="album py-5 bg-light">
    <div class="container">
        <form asp-action="index" method="get">
            <div class="input-group w-75 m-auto p-4">
                <div class="form-outline p-1">
                    <input name="SearchString" value="@ViewData["CurrentFilter"]" type="text" id="form1" class="form-control" />
                    <label class="form-label" for="form1">Search</label>
                </div>
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </form>
        @if (@ViewData["CurrentFilter"] is not null)
        {
            <a class="ms-3" asp-action="index">Back to full list</a>
        }
        <div class="row">
            @if (Model.Count() == 0)
            {
                <div>
                    <h2>Nothing found</h2>
                </div>
            }
            <div class="row">
                @foreach (var dish in Model)
                {
                    <div class="col-md-4 mb-4 d-flex align-items-stretch">
                        <div class="card">
                            <div class="bg-image overlay">
                                @if (dish.DishImage is null)
                                {
                                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/6-col/img%20(132).webp" class="card-img-top "
                                         alt="">

                                }
                                else
                                {
                                    <img src="@dish.DishImage" class="card-img-top "
                                         alt="">
                                }
                            </div>
                            <div class="card-body">                                
                                <h4 class="card-title">@dish.DishName</h4>
                                <p class="card-text">@dish.DishDescription</p>
                            </div>
                            <div class="d-flex justify-content-between m-3">
                                <a asp-controller="book" asp-action="detail" asp-route-id="@dish.DishId" type="button" class="btn btn-md btn-outline-secondary">Order</a>
                                <a type="button" asp-controller="dish" asp-action="Edit" asp-route-id="@dish.DishId" class="btn btn-md btn-outline-secondary">Edit</a>
                                @if (User.IsInRole("admin"))
                                {
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>